files:
  - source: /plugins/*/*_en.json
    translation: /%original_path%/%file_name%_%two_letters_code%.json
  - source: /themes/*/*_en.json
    translation: /%original_path%/%file_name%_%two_letters_code%.json
